name: evolve

channels:
  - conda-forge

dependencies:
  - python=3.11
  - numpy=1.26
  - pandas
  - scipy
  - matplotlib
  - seaborn
  - scikit-learn
  - scikit-image
  - opencv
  - tqdm
  - pyyaml
  - jupyterlab
  - ipykernel
  - pip

  - pip:
      - torch
      - torchvision
      - torchaudio
      - ultralytics
