name: evolve

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.11
  - numpy
  - scipy
  - pandas
  - matplotlib
  - seaborn
  - scipy
  - scikit-learn
  - opencv
  - jupyterlab
  - ipykernel
  - tqdm
  - pip
  - pip:
      - ultralytics
      - torch
