"""
EVOLVE – Luminance Distribution Analysis

This script analyzes the global luminance distribution of extracted frames.
It loads precomputed luminance statistics and:

1. Displays descriptive statistics
2. Plots the luminance histogram
3. Computes counts for predefined luminance categories

The goal is to characterize illumination conditions in the dataset
before performing stratified sampling.
"""

import pandas as pd
import matplotlib.pyplot as plt

# ------------------------------------------------------------------
# Configuration
# ------------------------------------------------------------------

# Path to the CSV file generated by compute_luminosity.py
CSV_PATH = "data/interim/luminosity_stats.csv"

# Output histogram path
OUTPUT_HIST_PATH = "data/interim/luminosity_histogram.png"

# ------------------------------------------------------------------
# Load luminance statistics
# ------------------------------------------------------------------

df = pd.read_csv(CSV_PATH)

# Display summary statistics for mean luminance
print("Descriptive statistics for mean luminance:")
print(df["mean_luminance"].describe())

# ------------------------------------------------------------------
# Plot luminance distribution
# ------------------------------------------------------------------

plt.figure(figsize=(8, 5))
plt.hist(df["mean_luminance"], bins=50)

plt.xlabel("Mean Luminance (Grayscale)")
plt.ylabel("Frequency")
plt.title("Distribution of Frame Luminance")

plt.tight_layout()
plt.savefig(OUTPUT_HIST_PATH)
plt.close()

print(f"Histogram saved to {OUTPUT_HIST_PATH}")

# ------------------------------------------------------------------
# Compute luminance category counts
# ------------------------------------------------------------------

# These thresholds were defined to stratify images
# into illumination difficulty levels.

very_low_count = (df["mean_luminance"] < 50).sum()
low_count = ((df["mean_luminance"] >= 50) & (df["mean_luminance"] < 125)).sum()
medium_count = (df["mean_luminance"] >= 125).sum()

print("Luminance category counts:")
print(f"Very low (<50): {very_low_count}")
print(f"Low (50–125): {low_count}")
print(f"Medium (>=125): {medium_count}")